name: color_blindness
description: Color Blindness on Flutter. Works with either color scheme or individual colors.
version: 0.2.0
homepage: https://github.com/bernaferrari/ColorBlindnessFlutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
